version: "3.8"

networks:
  gitea-net:
    driver: bridge

volumes:
  gitea_data:        # Penyimpanan repo & konfigurasi Gitea
  postgres_data:    # Penyimpanan data PostgreSQL

services:
  # -------------------------------------------------
  # PostgreSQL – database untuk Gitea
  # -------------------------------------------------
  gitea-db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env                     # ← ambil POSTGRES_* dari .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gitea-net
    # Uncomment untuk expose DB ke host (misalnya untuk pgAdmin)
    # ports:
    #   - "5432:5432"

  # -------------------------------------------------
  # Gitea – Git server
  # -------------------------------------------------
  gitea:
    image: gitea/gitea:1.22
    restart: unless-stopped
    depends_on:
      - gitea-db
    env_file:
      - .env                     # ← ambil GITEA_* dari .env
    environment:
      USER_UID: ${GITEA_UID}
      USER_GID: ${GITEA_GID}
      DB_TYPE: postgres
      DB_HOST: gitea-db:5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - gitea_data:/data
    ports:
      - "${GITEA_HTTP_PORT}:3000"   # UI Gitea
      - "${GITEA_SSH_PORT}:22"      # SSH Git
    networks:
      - gitea-net
  gitea-runner:
    image: gitea/act_runner:latest
    environment:
      GITEA_INSTANCE_URL: "http://192.168.1.5:3020"
      GITEA_RUNNER_REGISTRATION_TOKEN: "acxcCqHnZgvyoGIZHtuNE6UvyuSGaNdGMDsEKUW7"
      GITEA_RUNNER_NAME: "Gitea Runner"

    depends_on:
     - gitea
     - gitea-db
    volumes:
     - ./runner:/data
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - gitea-net 
